### PR TITLE
fix sign_with_frame so it actually works

### PR DESCRIPTION
**Pull request by eyooooo**

### CODE REVIEW

**Comment by kaleb-keny** [comment]
This didn't work @eyooooo

**Comment by kaleb-keny** [comment]
The below works thought
```
from copy import deepcopy
eip712_data                    = deepcopy(safe_tx.eip712_structured_data)
eip712_data["message"]["data"] = eip712_data["message"]["data"].hex()
signature                      = frame.manager.request_blocking('eth_signTypedData_v4', [account, eip712_data])
```

**Comment by kaleb-keny** [comment]
Hmmm pretty weird, i think it's just maybe we have different versions of brownie/ape-safe, below was the error
```
Malformed typed data
```
i'm on ubuntu
```
ape-safe==0.7.1
eth-brownie==1.19.2
python==3.8.16
```

**Comment by kaleb-keny** [comment]
> > This didn't work @eyooooo
> 
> good morning @kaleb-keny :) this change worked for me and our mutual friend (per his twitter thread). Curious what error you got?
> 
> Thanks

was corrected by our common twitter friend, fix is good @eyooooo

**Comment by banteg** [comment]
works in latest

**Pull request closed without merging**
